- 
    title: Ruby Relationships Without The Database
    hashtag: bamRubyNoDB
    date_published: 02/26/2010
    excerpt: Sometimes you don't need a database to persist data. If the dataset is small, and the model simple, a YAML file or static method will do.
- 
    title: Fat Free CRM Lead Form
    hashtag: bamFFCRM
    date_published: 07/24/09
    excerpt: I've been developing on Fat Free CRM for some time. To help out adoption of the platform, and my own business, I've written a plugin for wordpress to get leads into the CRM
- 
    title: Custom Routes With Shoulda
    hashtag: bamcrws
    date_published: 02/19/2010
    excerpt: In this post, I describe how to test that routes are resolving to the correct URL
- 
    title: Samba Server Integration
    hashtag: bamssi
    date_published: 07/14/2009
    excerpt: While on a trip to Beirut, I did some work setting up a file server
- 
    title: Improved Content Slider using MooTools
    hashtag: mooslide
    date_published: 05/27/2009
    excerpt: A great, open-sourced, horizontal slider using Mootools javascript framework.
-
    title: I Made it in to Inc Magazine
    hashtag: baminc
    date_published: 12/3/2009
    excerpt: I'm really fortunate to have been published in my favorite magazine.
-
    title: Thoughts on Developing
    hashtag: bamthoughts
    date_published: 7/16/2009
    excerpt: I've been a developer for a few years and see a few ways I think a little differently.
-
    title: TextMate Bundle for Asterisk Telephony
    hashtag: bamtmbundle
    date_published: 08/18/2008
    excerpt: I really enjoy telephony and writing the dialplan was getting tough without syntax highlighting. So, I wrote it and open sourced it!
